---@class SharedFoodEatingAssets
local Assets = {
	Bread = script.Bread,
	Burger = script.Burger,
	Fries = script.Fries,
	Pizza = script.Pizza,
	Steak = script.Steak,
	PieCherry = script.PieCherry,
	PieApple = script.PieApple,
	PieBlueberry = script.PieBlueberry,
	Cake = script.Cake,
	BirthdayCake = script.BirthdayCake,
	Pancaik = script.Pancaik,
	Waffle = script.Waffle,
	Muffin = script.Muffin,
	HotDog = script.HotDog,
	Taco = script.Taco,
	TurkeyLeg = script.TurkeyLeg,
	AppleGreen = script.AppleGreen,
	AppleRed = script.AppleRed,
	Grapes = script.Grapes,
	Ramen = script.Ramen,
}

return Assets
